server:
  port: 8888
  servlet:
    context-path: /chemicals  #设置项目访问路径

spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  #解决数据库字段带下划线字段自动转换驼峰命名
